### ISSUE TITLE
Issue with reassignment of variable

### ISSUE THREAD

**Issue by rkistner** [angelozerr/tern-lint#13]
```js
var b = {test: ''};
var a = '';
a = {test: function() {}};
a.test();
```

This produces an error "'test' is not a function" on the last line, since it thinks that `a.test` is a string.

This appears to be a bug in Tern itself. When autocompleting, it lists `test` as a function on `a`. However, afterwards, it thinks `a.test` is a string.

This issue is not critical, since it only happens when a variable is reassigned to something of a different type.

**Comment by angelozerr** [comment]
@rkistner could you retry it please, it seems that with last version of ternjs, I have not your problem?

**Comment by angelozerr** [comment]
@rkistner  it seems that tern has resolved this problem.@rkistner  it seems that tern has resolved this problem. I have added a test https://github.com/angelozerr/tern-lint/commit/aa2c3e1afd7f6060fcc4aeda898b1ee4505ef97a for this issue. 

I close this issue.
