### ISSUE TITLE
What is command line installation and usage?

### ISSUE THREAD

**Issue by paulvi** [angelozerr/tern-lint#26]
What is command line installation and usage?

**Comment by CestDiego** [comment]
@angelozerr I want to install this into my system but I can't install it with 

`npm install -g tern-lint` 

also it doesn't show in the npm website. Is this a bug? or is there a new non documented way of installing tern-lint ?

**Comment by angelozerr** [comment]
> also it doesn't show in the npm website. Is this a bug? 

No, I have not published tern-lint. I will do it soon.

**Comment by CestDiego** [comment]
I just thought as @paulvi said commented that it would look something like
`npm install -g tern-lint` and nobody said sth about it that it was supposed to be in npm.

Glad to know it'll be updated soon. I want to try is asap :D

**Comment by angelozerr** [comment]
> BTW how would I go and install it without npm? :O

You must just clone this git project and you can play with the web browser demos https://github.com/angelozerr/tern-lint/tree/master/demos

If you wish to use it with your editor, today iy exists Eclipse, Emacs and soon Atom which uses tern-lint.

**Comment by angelozerr** [comment]
@paulvi @CestDiego is it very interesting to have a command line installation? 

tern-lint is used with editors (Eclipse, Emacs, Atom today), so I tell me if command line installation could interest a lot of people? So I'm waiting for a lot of +1 to know if I will work on this issue.

**Comment by katspaugh** [comment]
Tern is an HTTP server, so I such command line tool would exist, it would be just `curl`ing to this server with the linted text as a JSON payload. I don't think this task should be pursued in the scope of this project. Let people create it as another integration plugin on par with editor plugins.

**Comment by angelozerr** [comment]
Thanks @katspaugh for your comment.

> Tern is an HTTP server,

Yes but we could use tern without server. We could have a tern-lint command which loops for JavaScript files (by using .tern-project loadEagerly for instance) and add it to the tern serevr instance, and after loop for each files stored in the tern server instance to validate each files. In this case, no need to have an HTTP server.

**Comment by katspaugh** [comment]
Yes, Tern can be used as a JavaScript library (though I don't think that library client would be easier to implement than an HTTP client).

An HTTP client can be written in any language in any language in a couple of lines.

For instance, a very crude example in bash:

```bash
#!/bin/bash

tern -p 9000
curl http://127.0.0.1:9000 "{ source: `cat $1` }"
```

**Comment by CestDiego** [comment]
Thing is I'm trying to use this with emacs... And I'm not sure how to
proceed. There is the other package for emacs but it depends on having this
installed.

**Comment by angelozerr** [comment]
Ok I have implemented a lint command with https://github.com/angelozerr/tern-lint/blob/master/bin/lint

See https://github.com/angelozerr/tern-lint/wiki/Command-Line

It's very basic but it works. Any contribution are welcome is somebody wish to improve it.
