### ISSUE TITLE
New validation: ReturnType not matching JSDoc @returns

### ISSUE THREAD

**Issue by p-bakker** [angelozerr/tern-lint#30]
Produce a builder marker when a function returns a different type as specified by it's JSDoc

**Comment by angelozerr** [comment]
To support this issue, I need the following PR https://github.com/marijnh/tern/pull/525 to know tha type comes from comment.

**Comment by angelozerr** [comment]
Done:

![](https://github.com/angelozerr/tern-lint/wiki/images/CodeMirrorAddon_JSDocReturns.png)

See https://github.com/angelozerr/tern-lint/wiki/Validation-JSDoc#returns
