### ISSUE TITLE
New Validation: Assignment of wrong type, according to JSDoc

### ISSUE THREAD

**Issue by p-bakker** [angelozerr/tern-lint#31]
Produce a builder marker when a variable gets assigned a value of a type that is not the same as the type defined in the JSDoc

**Comment by angelozerr** [comment]
To support this issue, I need the following PR https://github.com/marijnh/tern/pull/525 to know tha type comes from comment.

**Comment by angelozerr** [comment]
See https://github.com/angelozerr/tern-lint/wiki/Validation-JSDoc for configuration of JSDoc
