### ISSUE TITLE
Multiple signatures in jQuery

### ISSUE THREAD

**Issue by amiuhle** [angelozerr/tern-lint#40]
As described in marijnh/tern#543, using any other jQuery function than the defined `jQuery( selector [, context ] )` gives the following error:

```js
$(function() {
  // do something
}
// => Invalid argument at 1: cannot convert from Function.prototype to String.prototype
```

There are probably many more problems like this.

**Comment by amiuhle** [comment]
Related to #39

**Comment by angelozerr** [comment]
@amiuhle as jQuery can have complex signature, it should be done with a custom lint. The official tern jquery will not accept this lint code, so I have created https://github.com/angelozerr/tern-jquery-extension (which gives support for CSS selectors). Please create your issues with jQuery + validation at  https://github.com/angelozerr/tern-jquery-extension/issues

I close this issue.

**Comment by amiuhle** [comment]
Thanks
