### ISSUE TITLE
Invalid argument at 1: cannot convert from Function.prototype to String.prototype

### ISSUE THREAD

**Issue by VorT3x** [angelozerr/tern-lint#41]
Have this code (node.js + chai)

```javascript
 function(done) {
            User.create().exec(function(error, record) {
                expect(error).to.exist;
                done();
            });
        });
```

and get this error: `Invalid argument at 1: cannot convert from Function.prototype to String.prototype`

**Comment by angelozerr** [comment]
I think your error is because tern doesn't know which types is returned by `User.create()`. In this case it search an `exec` function which comes from `String`.

If you open completion after `User.create().exe`, is tern shows you exec function?

**Comment by angelozerr** [comment]
None answer. I close this issue.
