### ISSUE TITLE
Name is misleading

### ISSUE THREAD

**Issue by paulvi** [angelozerr/tern-lint#44]
I was not carefully looking at this, but after http://stackoverflow.com/questions/22218964/jsdoc-how-to-check-types-for-javascript I see that it is actually applying JSDoc

I feel that JSDoc should be shown in a name, or at least within first few line of README

**Comment by angelozerr** [comment]
In the README you have "tern-lint is able to use JSDoc annotations for the validation :"

**Comment by paulvi** [comment]
That was my first impression so.
