### ISSUE TITLE
Validation JSDoc does not work

### ISSUE THREAD

**Issue by paulvi** [angelozerr/tern-lint#46]
I tried https://github.com/angelozerr/tern-lint/wiki/Validation-JSDoc

```js
/**
 * @param {number} millis
 * @param {function} callback
 * */
function sleep(millis, callback) {
    setTimeout(function() {
        callback();
    }, millis);
}



sleep('a','b');

sleep('a','b');
```

using `.tern-project` as

```
{"libs":["ecma5"],"plugins":{
    "doc_comment":{"strong": true},
    "lint": {}
	"node":{}},"ide":{}
}
```

and then again going to project properties Tern -> Validation -> Lint
and with result like this:

```json
{	"ide":{},
	"doc_comment":{"strong":true},
	"lint":{},
	"plugins":{
		"lint":{
			"config":{}
		},
		"node":{}
	},
	"libs":["ecma5"]
}
```

How to make it work? 

I tried with 0.10 and
1.0.0.201507101609

**Comment by angelozerr** [comment]
What do you mean with doesnt work

**Comment by paulvi** [comment]
It was not showing error for `sleep('a','b')`

![](https://cloud.githubusercontent.com/assets/1614482/8641361/71fa651e-2946-11e5-9e3e-1c77496806b1.PNG)

**Comment by angelozerr** [comment]
For callback error you canuse Function instead ofusing function for @param to remove this error

**Comment by paulvi** [comment]
How to use Function ?

**Comment by angelozerr** [comment]
Today you musr write Function in the param instead of function 

I had created a basic PR to support function

See https://github.com/marijnh/tern/pull/561
See

**Comment by angelozerr** [comment]
> It was not showing error for `sleep('a','b')`

Please try with last version of 1.0.0-SNAPSHOT. It works for me?

**Comment by paulvi** [comment]
Testing with the current SNAPSHOT

```
{"ide":{},"doc_comment":{"strong":true},"lint":{},
"plugins":{
	"doc_comment":{"strong":true},
	"lint":{"config":{}},
	"node":{}
},"libs":["ecma5"]}
```

The first time I change `.tern-project` there is Yes-No Dialog, but later there is no,
e.g. when I add empty line.

![1](https://cloud.githubusercontent.com/assets/1614482/9228403/e8c99766-414a-11e5-9d3a-63ec0ccbf580.PNG)

>  [Lint]: 'callback' is not a function

and new weird
![2](https://cloud.githubusercontent.com/assets/1614482/9228421/0105a112-414b-11e5-8ea0-378b41bb256b.PNG)

> [Lint]: Invalid argument at 1: cannot convert from String.prototype to Buffer.prototype

**Comment by paulvi** [comment]
After changing function to Function

![3](https://cloud.githubusercontent.com/assets/1614482/9228521/6fc49284-414b-11e5-800a-5176a1e69cd8.PNG)

There is correct error for `sleep('a','b');`
but for `callback();` again

> [Lint]: 'callback' is not a function

**Comment by angelozerr** [comment]
> The first time I change .tern-project there is Yes-No Dialog, but later there is no,
e.g. when I add empty line.

What is the problem with that, it's the same behaviour than other WTP Validator (HTML, XML, etc)

> and new weird

You mean that res.end('') must not raise error?

> There is correct error for sleep('a','b'); but for callback(); again

Yes I know See marijnh/tern#561

**Comment by angelozerr** [comment]
@paulvi if you have problem with validation like res.end('') , please create an issues at https://github.com/angelozerr/tern-lint/issues

It should be very cool if you could play with lint + node and creates a lto of issues to improve it.

Can we close this issue?

**Comment by angelozerr** [comment]
@paulvi for you rproblem with res.end('') , I have created a PR for tern https://github.com/marijnh/tern/pull/602/files#diff-44a33130248596d4bb0ec800a79bd660R454

**Comment by angelozerr** [comment]
@paulvi can we close this issue?

**Comment by paulvi** [comment]
well, technically we should close this when those 2 referenced issues are closed. It is up to you.

**Comment by angelozerr** [comment]
Ok, but for Function I'm afraid that tern will not support it. I don't know?

**Comment by paulvi** [comment]
closing as becoming to long.
