### ISSUE TITLE
[Lint]: 'callback' is not a function

### ISSUE THREAD

**Issue by paulvi** [angelozerr/tern-lint#47]
for code 

```
/**
 * @param {number} millis
 * @param {function} callback
 * */
function sleep(millis, callback) {
    setTimeout(function() {
        callback();
    }, millis);
}



sleep('a','b');

sleep('a','b');

```

I got only one error for `callback();` line:

> [Lint]: 'callback' is not a function

.tern-project

```
{	"ide":{},
	"doc_comment":{"strong":true},
	"lint":{},
	"plugins":{
		"lint":{
			"config":{}
		},
		"node":{}
	},
	"libs": ["ecma5","browser"]
}
```

I tried with 0.10 and
1.0.0.201507101609

**Comment by paulvi** [comment]
![lint47](https://cloud.githubusercontent.com/assets/1614482/8641361/71fa651e-2946-11e5-9e3e-1c77496806b1.PNG)

**Comment by angelozerr** [comment]
Its because doc_comment dorsnt support function param ihad created a pr for tern but it seems param function is not official

**Comment by angelozerr** [comment]
@paulvi with last version of ternjs it works now. But you must use upper case like:

@param {Function} callback

**Comment by paulvi** [comment]
What is the difference between `Function` and `function` ?

**Comment by angelozerr** [comment]
I don't know. When I have tested, it works like this
