### ISSUE TITLE
Type mismatch error messages should show actual type rather than type.protoype.

### ISSUE THREAD

**Issue by dmitryKovchin** [angelozerr/tern-lint#50]
I found that function getTypeName(type) returns type.prototype.name, but I expect to see actual type. For some cases it looks too weird:
![wrongtypeisdisplaying](https://cloud.githubusercontent.com/assets/3449165/9474296/a14e9ac0-4b14-11e5-8416-ca57fb6117f8.png)

Here since both Employee and Customer have the same proto we get 'Can't convert Person to Person'. But if we used actual types it would be 'Can't convert Employee to Customer', that makes much more sense for me.
I would suggest to change functiongetTypeName(type) in lint.js: 'return (type.proto) ? type.proto.name : "Unknown type";'  -> 'return type.name;'

**Comment by angelozerr** [comment]
@dmitryKovchin is it possible for you to create a PR (to check that your suggestion doesn't break tests) and add a new tests + demo. Thanks!

**Comment by angelozerr** [comment]
Dne with https://github.com/angelozerr/tern-lint/pull/51
