### ISSUE TITLE
jQuery end() function is not valid

### ISSUE THREAD

**Issue by mquan86** [angelozerr/tern-lint#53]
Use jQuery library with below code:

    $( "#content" )
    .find( "h3" )
    .eq( 2 )
        .html( "new text for the third h3!" )
        .end() // Restores the selection to all h3s in #content
    .eq( 0 )
        .html( "new text for the first h3!" );

The end() method is marked as invalid with error: Unknown property 'end'

**Comment by angelozerr** [comment]
This problems comes from with jQuery.fn.html can have several signatures. I have created a PR at https://github.com/marijnh/tern/pull/630 to fix this problem.

**Comment by angelozerr** [comment]
https://github.com/ternjs/tern/pull/630 was accepted, please update tern and it should work.
