### ISSUE TITLE
How to integrate with vim

### ISSUE THREAD

**Issue by allan-simon** [angelozerr/tern-lint#61]
Hello thanks for this project which seems pretty cool
I guess that if you haven't added in the README how to integrate it with vim it's because you don't know, but if somebody out there feel like explaining how to do it, I will be really thankful :)

**Comment by angelozerr** [comment]
@allan-simon I close this issue because it is not linked to tern-lint. I had created an issue at https://github.com/marijnh/tern_for_vim/issues/105 but @marijnh has not time to do that.

**Comment by allan-simon** [comment]
ok, thanks for the link,  for my ticket , I created as I've seen that in the README you were explaining how to use it for  emacs / atom etc. so one may have wanted to create a PR to update the readme to link to their vim plugin / blogpost
