### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by bmihelac** [angelozerr/tern-lint#65]
It looks like there are missing dependencies:

  minimatch
  glob

**Comment by angelozerr** [comment]
Why are you saying that. tern-lint doesn't use minimatch, glob. It's tern which uses that.

**Comment by bmihelac** [comment]
yes, I tried to use command line

**Comment by angelozerr** [comment]
ok for the moment, do "npm install glob" and "npm install minimatch". I will fix that ASAP.
