### ISSUE TITLE
Excessive output when running from command line

### ISSUE THREAD

**Issue by bmihelac** [angelozerr/tern-lint#66]
Hi,

following [SO question](http://stackoverflow.com/questions/33809829/javascript-import-handle-undefined/) I created little repository to test tern-lint.

Repository is available on github:

https://github.com/bmihelac/test-js-import-undefined/tree/tern-lint

I noticed that running from *tmp* directory which contains only one file with only one export declaration lint output is very big (over 3500 lines):

I included output:
https://github.com/bmihelac/test-js-import-undefined/blob/tern-lint/tmp/lint.txt

Maybe I am just missing something obvious?

**Comment by angelozerr** [comment]
I have not this problem? Which line command do you use?

**Comment by bmihelac** [comment]
OK thanks I guess this one is safe to close as upgrading Node to 4.1 (was iojs-v2.2.1 *blush*) there is only one message, updated https://github.com/bmihelac/test-js-import-undefined/blob/tern-lint/tmp/lint.txt
