### ISSUE TITLE
Need a way to tell tern-lint that wish he would to silent

### ISSUE THREAD

**Issue by repsac-by** [angelozerr/tern-lint#68]
![2016-01-27 17-16-45](https://cloud.githubusercontent.com/assets/4984191/12616277/70795580-c51b-11e5-94ba-e3380ca0d23a.png)

Of course it's not his fault, and not fully documented functions.
![2016-01-27 17-16-58](https://cloud.githubusercontent.com/assets/4984191/12616282/73b8d81a-c51b-11e5-85ca-c27475a5b797.png)

But really listen() has 3 varieties:

https://nodejs.org/api/http.html#http_server_listen_handle_callback
`server.listen(handle[, callback])`

https://nodejs.org/api/http.html#http_server_listen_path_callback
`server.listen(path[, callback])`

https://nodejs.org/api/http.html#http_server_listen_port_hostname_backlog_callback
`server.listen(port[, hostname][, backlog][, callback])`

But it would be great to have a Directive which could suppress the error

**Comment by angelozerr** [comment]
@repsac-by tern-lint gives the capability to implement your linter. https://github.com/angelozerr/tern-node-extension supports for instance require module validation.

Please move your issue to https://github.com/angelozerr/tern-node-extension
