### ISSUE TITLE
Validating in Eclipse

### ISSUE THREAD

**Issue by siluri** [angelozerr/tern-lint#77]
I got this issue by validating JS Resources.

```
An internal error occurred during: "Validating".
tern.server.protocol.lint.TernLintQuery.setFix(Z)V
```

i use nodejs 6.9.2 and got warning by install tern-lint

```
>npm install -g tern-lint
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher
to avoid a RegExp DoS issue
```

**Comment by angelozerr** [comment]
It's an issue for tern.java. Please create an issue in tern.java by giving version of tern.java, of Eclipse and tell me how to reproduce this error (the content of js file, etc)
